LangString addOrReinstall ${LANG_FRENCH} "Ajouter ou réinstaller des composants"
LangString JotLuckFileType ${LANG_FRENCH} "Note Markdown ou texte"
LangString JotLuckDocumentType ${LANG_FRENCH} "Document Word, PDF ou Excel importable"
LangString alreadyInstalled ${LANG_FRENCH} "Déjà installé"
LangString alreadyInstalledLong ${LANG_FRENCH} "${PRODUCTNAME} ${VERSION} est déjà installé. Sélectionnez l’opération à effectuer, puis cliquez sur Suivant."
LangString appRunning ${LANG_FRENCH} "{{product_name}} est en cours d’exécution. Fermez-le, puis réessayez."
LangString appRunningOkKill ${LANG_FRENCH} "{{product_name}} est en cours d’exécution.$\nCliquez sur OK pour l’arrêter."
LangString chooseMaintenanceOption ${LANG_FRENCH} "Choisissez l’opération de maintenance à effectuer."
LangString choowHowToInstall ${LANG_FRENCH} "Choisissez comment installer ${PRODUCTNAME}."
LangString createDesktop ${LANG_FRENCH} "Créer un raccourci sur le Bureau"
LangString dontUninstall ${LANG_FRENCH} "Ne pas désinstaller"
LangString dontUninstallDowngrade ${LANG_FRENCH} "Ne pas désinstaller (la rétrogradation sans désinstallation est désactivée)"
LangString failedToKillApp ${LANG_FRENCH} "Impossible d’arrêter {{product_name}}. Fermez-le, puis réessayez."
LangString installingWebview2 ${LANG_FRENCH} "Installation de Microsoft Edge WebView2 Runtime..."
LangString newerVersionInstalled ${LANG_FRENCH} "Une version plus récente de ${PRODUCTNAME} est déjà installée. L’installation d’une version antérieure est déconseillée. Si nécessaire, désinstallez d’abord la version actuelle. Sélectionnez une opération, puis cliquez sur Suivant."
LangString older ${LANG_FRENCH} "antérieure"
LangString olderOrUnknownVersionInstalled ${LANG_FRENCH} "Une version $R4 de ${PRODUCTNAME} est installée. Il est recommandé de la désinstaller avant de continuer. Sélectionnez une opération, puis cliquez sur Suivant."
LangString silentDowngrades ${LANG_FRENCH} "La rétrogradation est désactivée ; l’installation silencieuse ne peut pas continuer. Utilisez l’installateur graphique.$\n"
LangString unableToUninstall ${LANG_FRENCH} "Impossible de désinstaller."
LangString uninstallApp ${LANG_FRENCH} "Désinstaller ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_FRENCH} "Désinstaller avant l’installation"
LangString unknown ${LANG_FRENCH} "inconnue"
LangString webview2AbortError ${LANG_FRENCH} "Impossible d’installer Microsoft Edge WebView2 Runtime, requis pour démarrer ${PRODUCTNAME}. Connectez-vous à Internet et réessayez, ou utilisez un installateur hors ligne incluant WebView2 Runtime."
LangString webview2DownloadError ${LANG_FRENCH} "Impossible de télécharger l’installateur de Microsoft Edge WebView2 Runtime. Erreur : $0. Vérifiez la connexion réseau et réessayez, ou utilisez l’installateur hors ligne."
LangString webview2DownloadSuccess ${LANG_FRENCH} "Installateur de Microsoft Edge WebView2 Runtime téléchargé"
LangString webview2Downloading ${LANG_FRENCH} "Téléchargement de l’installateur de Microsoft Edge WebView2 Runtime..."
LangString webview2InstallError ${LANG_FRENCH} "Échec de l’installation de Microsoft Edge WebView2 Runtime (code de sortie $1). Connectez-vous à Internet et réessayez, ou utilisez l’installateur hors ligne."
LangString webview2InstallSuccess ${LANG_FRENCH} "Microsoft Edge WebView2 Runtime installé"
LangString deleteAppData ${LANG_FRENCH} "Supprimer les données de l’application"
