LangString addOrReinstall ${LANG_JAPANESE} "コンポーネントを追加／再インストール"
LangString JotLuckFileType ${LANG_JAPANESE} "Markdown またはテキストノート"
LangString JotLuckDocumentType ${LANG_JAPANESE} "インポート可能な Word、PDF、Excel 文書"
LangString alreadyInstalled ${LANG_JAPANESE} "インストール済み"
LangString alreadyInstalledLong ${LANG_JAPANESE} "${PRODUCTNAME} ${VERSION} はすでにインストールされています。実行する操作を選び、［次へ］をクリックしてください。"
LangString appRunning ${LANG_JAPANESE} "{{product_name}} が実行中です。終了してからもう一度お試しください。"
LangString appRunningOkKill ${LANG_JAPANESE} "{{product_name}} が実行中です。$\n［OK］をクリックすると終了します。"
LangString chooseMaintenanceOption ${LANG_JAPANESE} "実行するメンテナンス操作を選んでください。"
LangString choowHowToInstall ${LANG_JAPANESE} "${PRODUCTNAME} のインストール方法を選んでください。"
LangString createDesktop ${LANG_JAPANESE} "デスクトップショートカットを作成"
LangString dontUninstall ${LANG_JAPANESE} "アンインストールしない"
LangString dontUninstallDowngrade ${LANG_JAPANESE} "アンインストールしない（このインストーラーでは未削除のままのダウングレードはできません）"
LangString failedToKillApp ${LANG_JAPANESE} "{{product_name}} を終了できませんでした。手動で終了してからもう一度お試しください。"
LangString installingWebview2 ${LANG_JAPANESE} "Microsoft Edge WebView2 Runtime をインストールしています..."
LangString newerVersionInstalled ${LANG_JAPANESE} "新しいバージョンの ${PRODUCTNAME} がすでにインストールされています。古いバージョンのインストールは推奨されません。必要な場合は現在のバージョンを先にアンインストールしてください。操作を選び、［次へ］をクリックしてください。"
LangString older ${LANG_JAPANESE} "古い"
LangString olderOrUnknownVersionInstalled ${LANG_JAPANESE} "${PRODUCTNAME} の $R4 バージョンがインストールされています。現在のバージョンを先にアンインストールすることを推奨します。操作を選び、［次へ］をクリックしてください。"
LangString silentDowngrades ${LANG_JAPANESE} "このインストーラーではダウングレードが無効なため、サイレントインストールを続行できません。グラフィカルインストーラーを使用してください。$\n"
LangString unableToUninstall ${LANG_JAPANESE} "アンインストールできません。"
LangString uninstallApp ${LANG_JAPANESE} "${PRODUCTNAME} をアンインストール"
LangString uninstallBeforeInstalling ${LANG_JAPANESE} "インストール前にアンインストール"
LangString unknown ${LANG_JAPANESE} "不明"
LangString webview2AbortError ${LANG_JAPANESE} "Microsoft Edge WebView2 Runtime をインストールできませんでした。${PRODUCTNAME} の起動に必要です。インターネットへ接続して再試行するか、WebView2 Runtime を含むオフラインインストーラーを使用してください。"
LangString webview2DownloadError ${LANG_JAPANESE} "Microsoft Edge WebView2 Runtime インストーラーをダウンロードできませんでした。エラー：$0。ネットワーク接続を確認して再試行するか、オフラインインストーラーを使用してください。"
LangString webview2DownloadSuccess ${LANG_JAPANESE} "Microsoft Edge WebView2 Runtime インストーラーをダウンロードしました"
LangString webview2Downloading ${LANG_JAPANESE} "Microsoft Edge WebView2 Runtime インストーラーを取得しています..."
LangString webview2InstallError ${LANG_JAPANESE} "Microsoft Edge WebView2 Runtime のインストールに失敗しました（終了コード $1）。インターネットへ接続して再試行するか、オフラインインストーラーを使用してください。"
LangString webview2InstallSuccess ${LANG_JAPANESE} "Microsoft Edge WebView2 Runtime をインストールしました"
LangString deleteAppData ${LANG_JAPANESE} "アプリケーションデータを削除"
