LangString addOrReinstall ${LANG_KOREAN} "구성 요소 추가/다시 설치"
LangString JotLuckFileType ${LANG_KOREAN} "Markdown 또는 텍스트 노트"
LangString JotLuckDocumentType ${LANG_KOREAN} "가져올 수 있는 Word, PDF 또는 Excel 문서"
LangString alreadyInstalled ${LANG_KOREAN} "이미 설치됨"
LangString alreadyInstalledLong ${LANG_KOREAN} "${PRODUCTNAME} ${VERSION}이(가) 이미 설치되어 있습니다. 수행할 작업을 선택하고 다음을 클릭하세요."
LangString appRunning ${LANG_KOREAN} "{{product_name}}이(가) 실행 중입니다. 먼저 닫은 뒤 다시 시도하세요."
LangString appRunningOkKill ${LANG_KOREAN} "{{product_name}}이(가) 실행 중입니다.$\n확인을 클릭하면 종료합니다."
LangString chooseMaintenanceOption ${LANG_KOREAN} "수행할 유지 관리 작업을 선택하세요."
LangString choowHowToInstall ${LANG_KOREAN} "${PRODUCTNAME} 설치 방법을 선택하세요."
LangString createDesktop ${LANG_KOREAN} "바탕 화면 바로 가기 만들기"
LangString dontUninstall ${LANG_KOREAN} "제거하지 않음"
LangString dontUninstallDowngrade ${LANG_KOREAN} "제거하지 않음(이 설치 프로그램은 제거하지 않은 다운그레이드를 허용하지 않음)"
LangString failedToKillApp ${LANG_KOREAN} "{{product_name}}을(를) 종료하지 못했습니다. 직접 닫은 뒤 다시 시도하세요."
LangString installingWebview2 ${LANG_KOREAN} "Microsoft Edge WebView2 Runtime 설치 중..."
LangString newerVersionInstalled ${LANG_KOREAN} "더 최신 버전의 ${PRODUCTNAME}이(가) 이미 설치되어 있습니다. 이전 버전 설치는 권장하지 않습니다. 필요한 경우 현재 버전을 먼저 제거하세요. 작업을 선택하고 다음을 클릭하세요."
LangString older ${LANG_KOREAN} "이전"
LangString olderOrUnknownVersionInstalled ${LANG_KOREAN} "시스템에 ${PRODUCTNAME} $R4 버전이 설치되어 있습니다. 설치 전에 현재 버전을 제거하는 것이 좋습니다. 작업을 선택하고 다음을 클릭하세요."
LangString silentDowngrades ${LANG_KOREAN} "이 설치 프로그램에서는 다운그레이드를 사용할 수 없어 자동 설치를 계속할 수 없습니다. 그래픽 설치 프로그램을 사용하세요.$\n"
LangString unableToUninstall ${LANG_KOREAN} "제거할 수 없습니다."
LangString uninstallApp ${LANG_KOREAN} "${PRODUCTNAME} 제거"
LangString uninstallBeforeInstalling ${LANG_KOREAN} "설치 전에 제거"
LangString unknown ${LANG_KOREAN} "알 수 없음"
LangString webview2AbortError ${LANG_KOREAN} "Microsoft Edge WebView2 Runtime을 설치할 수 없습니다. ${PRODUCTNAME} 실행에 필요합니다. 인터넷에 연결해 다시 시도하거나 WebView2 Runtime이 포함된 오프라인 설치 프로그램을 사용하세요."
LangString webview2DownloadError ${LANG_KOREAN} "Microsoft Edge WebView2 Runtime 설치 프로그램을 다운로드할 수 없습니다. 오류: $0. 네트워크 연결을 확인해 다시 시도하거나 오프라인 설치 프로그램을 사용하세요."
LangString webview2DownloadSuccess ${LANG_KOREAN} "Microsoft Edge WebView2 Runtime 설치 프로그램 다운로드 완료"
LangString webview2Downloading ${LANG_KOREAN} "Microsoft Edge WebView2 Runtime 설치 프로그램 가져오는 중..."
LangString webview2InstallError ${LANG_KOREAN} "Microsoft Edge WebView2 Runtime 설치에 실패했습니다(종료 코드 $1). 인터넷에 연결해 다시 시도하거나 오프라인 설치 프로그램을 사용하세요."
LangString webview2InstallSuccess ${LANG_KOREAN} "Microsoft Edge WebView2 Runtime 설치 완료"
LangString deleteAppData ${LANG_KOREAN} "애플리케이션 데이터 삭제"
